# Generated by Django 4.2.5 on 2024-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('host', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField(max_length=100)),
                ('round', models.IntegerField(default=1)),
                ('outround', models.BooleanField(default=False)),
                ('motions', models.TextField(max_length=400, null=True)),
                ('adjudicator_view_accessible', models.BooleanField(default=False)),
                ('team_view_accessible', models.BooleanField(default=False)),
                ('participant_view_accessible', models.BooleanField(default=False)),
                ('ordered_speaker_view_accessible', models.BooleanField(default=False)),
                ('ordered_team_view_accessible', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
