# Generated by Django 4.2.5 on 2024-01-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_tournament_r1_view_accessible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='motions',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
