# Generated by Django 4.2.5 on 2024-03-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_tournament_final_view_accessible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='final_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Final Turunu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='onalti_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Çeyrek Final Turunu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='oniki_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Kısmi Yarı Turunu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='otuziki_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Ön Çeyrek Turunu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='sekiz_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Yarı Final Turunu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='yirmidort_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Kısmi Çeyrek Turunu Görünür Yap'),
        ),
    ]
