# Generated by Django 4.2.5 on 2024-04-09 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_alter_tournament_final_view_accessible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='adjudicator_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Juri Listesini Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ordered_speaker_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Konuşmacı Puanlarını Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='ordered_team_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Takım Puanlarını Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participant_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Katılımcı Listesini Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='r1_view_accessible',
            field=models.BooleanField(default=False, verbose_name='1. Raundu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='r2_view_accessible',
            field=models.BooleanField(default=False, verbose_name='2. Raundu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='r3_view_accessible',
            field=models.BooleanField(default=False, verbose_name='3. Raundu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='r4_view_accessible',
            field=models.BooleanField(default=False, verbose_name='4. Raundu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='r5_view_accessible',
            field=models.BooleanField(default=False, verbose_name='5. Raundu Görünür Yap'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='team_view_accessible',
            field=models.BooleanField(default=False, verbose_name='Takım Listesini Görünür Yap'),
        ),
    ]
