# Generated by Django 4.2.5 on 2024-01-15 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjudicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('commitee', models.BooleanField(null=True)),
                ('experience', models.TextField(null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourn_info.adjudicator')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50, null=True)),
                ('r1_pt', models.IntegerField()),
                ('r2_pt', models.IntegerField()),
                ('r3_pt', models.IntegerField()),
                ('r4_pt', models.IntegerField()),
                ('r5_pt', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='main_page.tournament')),
            ],
            options={
                'permissions': (('set_r1_pt', "can set round 1's team points"), ('set_r2_pt', "can set round 2's team points"), ('set_r3_pt', "can set round 3's team points"), ('set_r4_pt', "can set round 4's team points"), ('set_r5_pt', "can set round 5's team points")),
            },
        ),
        migrations.CreateModel(
            name='TeamAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('OG', 'Opening Government'), ('OO', 'Opening Opposition'), ('CG', 'Closing Government'), ('CO', 'Closing Opposition')], max_length=2)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourn_info.lobby')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourn_info.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50, null=True)),
                ('r1_spkr', models.IntegerField()),
                ('r2_spkr', models.IntegerField()),
                ('r3_spkr', models.IntegerField()),
                ('r4_spkr', models.IntegerField()),
                ('r5_spkr', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tourn_info.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.tournament')),
            ],
            options={
                'permissions': (('set_r1_spkr', "can set round 1's speaker points"), ('set_r2_spkr', "can set round 2's speaker points"), ('set_r3_spkr', "can set round 3's speaker points"), ('set_r4_spkr', "can set round 4's speaker points"), ('set_r5_spkr', "can set round 5's speaker points")),
            },
        ),
        migrations.AddField(
            model_name='lobby',
            name='teams',
            field=models.ManyToManyField(through='tourn_info.TeamAssignment', to='tourn_info.team'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.tournament'),
        ),
    ]
