# Generated by Django 4.2.5 on 2024-01-15 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourn_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamassignment',
            name='adjudicator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourn_info.adjudicator'),
        ),
    ]
