# Generated by Django 4.2.5 on 2024-01-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourn_info', '0002_teamassignment_adjudicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='co',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='og',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='oo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adjudicator',
            name='commitee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adjudicator',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='r1_spkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='r2_spkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='r3_spkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='r4_spkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='r5_spkr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='r1_pt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='r2_pt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='r3_pt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='r4_pt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='r5_pt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
