# Generated by Django 4.2.5 on 2024-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourn_info', '0004_alter_participant_options_alter_participant_r1_spkr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='outround',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
