# Generated by Django 4.2.5 on 2024-04-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourn_info', '0006_lobby_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='total_speaker_points',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='team',
            name='total_points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
