# Generated by Django 4.2.5 on 2024-04-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourn_info', '0007_participant_total_speaker_points_team_total_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_speaker_points',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
