# Generated by Django 4.2.5 on 2024-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourn_info', '0008_team_total_speaker_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjudicator',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
