# Generated by Django 4.2.5 on 2024-06-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_tournament_adjudicator_view_accessible_and_more'),
        ('tourn_info', '0010_remove_adjudicator_commitee_remove_lobby_adjudicator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_strict', models.BooleanField(default=False)),
                ('adjudicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourn_info.adjudicator')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourn_info.participant')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tourn_info.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_page.tournament')),
            ],
        ),
    ]
